### ISSUE TITLE
Include a list of installed packages required for full install

### ISSUE THREAD

**Issue by clbarnes** [PyMesh/PyMesh#116]
Right now users are just running cmake and having to parse the output and install requirements with obtuse names one at a time as errors are hit.

So far I have (with the package name on ubuntu 18.04)

- GMP (libgmp3-dev)
- MPFR (libmpfr-dev)
- TBB (libtbb-dev)
- boost thread (libboost-thread-dev)
- boost system (libboost-system-dev)
- qmake (qt5-qmake)

**Comment by qnzhou** [comment]
Thanks for the suggestion!  Just to clarify, do you mean to include a list of libraries that is not included in the [third_party](https://github.com/qnzhou/PyMesh/tree/master/third_party) directory?  I.e. the second level of dependencies?

(I do not think qmake is needed.)

**Comment by clbarnes** [comment]
That's it - work back far enough up the dependency tree until you hit a package manager which can figure out its own dependencies (in my case, apt). This way all the install instructions can be found in one place rather than having to run a partial build, hit an error, parse the log, google how to install the missing component, and so on. 

You're probably right that qmake isn't needed - the installation got past it just throwing a warning, but I wasn't sure if not having it would disable some features.

Another useful piece of documentation would be which parts of the installation can be done once for all the virtual environments you want to use pymesh in, and which parts need to be repeated for every virtualenv.
