### ISSUE TITLE
Compile Error: 'TriangleWrapper' was not declared in this scope; 'triangle' was not declared in this scope.

### ISSUE THREAD

**Issue by szx0112** [PyMesh/PyMesh#121]
**I have spend two days to build and install PyMesh on my system (ubuntu 16.04), but still cannot make it. Here is my third party cmake resutls:**
`-- Boost version: 1.58.0
-- Using system boost
abort: repository /home/szx/PyMesh/third_party not found!
abort: repository /home/szx/PyMesh/third_party not found!
-- Standard libraries to link to explicitly: none
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
-- Found Qt4: /usr/bin/qmake (found version "4.8.7") 
-- A version of Pastix has been found but pastix_nompi.h does not exist in the include directory. Because Eigen tests require a version without MPI, we disable the Pastix backend.
CMake Warning (dev) in eigen/bench/spbench/CMakeLists.txt:
  A logical block opening on the line

    /home/szx/PyMesh/third_party/eigen/bench/spbench/CMakeLists.txt:51 (if)

  closes on the line

    /home/szx/PyMesh/third_party/eigen/bench/spbench/CMakeLists.txt:63 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- ************************************************************
-- ***    Eigen's unit tests configuration summary          ***
-- ************************************************************
-- 
-- Build type:        Release
-- Build site:        szx-macpro
-- Build string:      linux-4.13.0-43-generic-_-5.4.0-sse2-64bit
-- Enabled backends:  GoogleHash,  Adolc,  MPFR C++,  fftw, 
-- Disabled backends: OpenGL, 
-- Default order:     Column-major
-- Maximal matrix/vector size: 320
-- SSE2:              Using architecture defaults
-- SSE3:              Using architecture defaults
-- SSSE3:             Using architecture defaults
-- SSE4.1:            Using architecture defaults
-- SSE4.2:            Using architecture defaults
-- AVX:               Using architecture defaults
-- FMA:               Using architecture defaults
-- AVX512:            Using architecture defaults
-- Altivec:           Using architecture defaults
-- VSX:               Using architecture defaults
-- ARM NEON:          Using architecture defaults
-- ARMv8 NEON:        Using architecture defaults
-- S390X ZVECTOR:     Using architecture defaults
-- C++11:             OFF
-- SYCL:              OFF
-- CUDA:              OFF
-- 

-- ************************************************************
-- 
-- Configured Eigen 3.3.4
-- 
-- Some things you can do now:
-- --------------+--------------------------------------------------------------
-- Command       |   Description
-- --------------+--------------------------------------------------------------
-- make install  | Install Eigen. Headers will be installed to:
--               |     <CMAKE_INSTALL_PREFIX>/<INCLUDE_INSTALL_DIR>
--               |   Using the following values:
--               |     CMAKE_INSTALL_PREFIX: /home/szx/PyMesh/third_party/../python/pymesh/third_party
--               |     INCLUDE_INSTALL_DIR:  include/eigen3
--               |   Change the install location of Eigen headers using:
--               |     cmake . -DCMAKE_INSTALL_PREFIX=yourprefix
--               |   Or:
--               |     cmake . -DINCLUDE_INSTALL_DIR=yourdir
-- make doc      | Generate the API documentation, requires Doxygen & LaTeX
-- make check    | Build and run the unit-tests. Read this page:
--               |   http://eigen.tuxfamily.org/index.php?title=Tests
-- make blas     | Build BLAS library (not the same thing as Eigen)
-- make uninstall| Removes files installed by make install
-- --------------+--------------------------------------------------------------
-- 
-- 
-- ========== qhull Build Information ==========
-- Build Version:                             7.2.0
-- Install Prefix (CMAKE_INSTALL_PREFIX):     /home/szx/PyMesh/third_party/../python/pymesh/third_party
-- Binary Directory (BIN_INSTALL_DIR):        /home/szx/PyMesh/third_party/../python/pymesh/third_party/bin
-- Library Directory (LIB_INSTALL_DIR):       /home/szx/PyMesh/third_party/../python/pymesh/third_party/lib
-- Include Directory (INCLUDE_INSTALL_DIR):   /home/szx/PyMesh/third_party/../python/pymesh/third_party/include
-- Documentation Directory (DOC_INSTALL_DIR): /home/szx/PyMesh/third_party/../python/pymesh/third_party/share/doc/qhull
-- Man Pages Directory (MAN_INSTALL_DIR):     /home/szx/PyMesh/third_party/../python/pymesh/third_party/share/man/man1
-- Build Type (CMAKE_BUILD_TYPE):             Release
-- To override these options, add -D{OPTION_NAME}=... to the cmake command
--   Build the debug targets                  -DCMAKE_BUILD_TYPE=Debug
-- 
-- To build and install qhull, enter "make" and "make install"
-- To smoketest qhull, enter "ctest"
-- 
-- A cache variable, namely SCOTCH_DIR, has been set to specify the install directory of SCOTCH
-- Looking for scotch -- scotch.h not found
-- Looking for scotch -- lib scotch not found
-- Looking for scotch -- lib scotcherrexit not found
-- Could NOT find SCOTCH (missing: SCOTCH_LIBRARIES SCOTCH_WORKS) 
CMake Warning at mmg/CMakeLists.txt:208 (MESSAGE):
  Scotch library not found:Using scotch reduce the execution time of mmg3d
  (see https://gforge.inria.fr/frs/?group_id=248 to download it).If you have
  already installed Scotch and want to use it, please set the CMake variable
  or environment variable SCOTCH_DIR to your scotch directory.

-- Could NOT find ELAS (missing: ELAS_INCLUDE_DIR ELAS_LIBRARY) 
-- Could NOT find ELAS (missing: ELAS_INCLUDE_DIR ELAS_LIBRARY) 
/home/szx/PyMesh/third_party/mmg/src/mmg2d
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg2d/libmmg2d.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg2d/libmmgtypes.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmgs/libmmgs.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmgs/libmmgtypes.h
-- Vertex insertion by delaunay kernel
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg3d/libmmg3d.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg3d/libmmgtypes.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg//libmmgf.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg2d//libmmg2d.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg2d//libmmgtypes.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmgs//libmmgs.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmgs//libmmgtypes.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg3d//libmmg3d.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg/mmg3d//libmmgtypes.h
-- Up-to-date: /home/szx/PyMesh/third_party/build/mmg/include/mmg//libmmg.h
== CMake setup ==
== CMake setup (DONE) ==

CMake Deprecation Warning at cgal/Installation/CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

== Setting paths ==
-- Build CGAL from git-branch: master
-- Removed not-a-package: .gitattributes;.github;.gitignore;.travis;.travis.yml;Documentation;INSTALL.md;LICENSE.md;Miscellany;README.md
-- Installation package directory: /home/szx/PyMesh/third_party/cgal/Installation
-- Maintenance package directory: /home/szx/PyMesh/third_party/cgal/Maintenance
-- Core package directory: /home/szx/PyMesh/third_party/cgal/Core
-- Packagenames: AABB_tree;Advancing_front_surface_reconstruction;Algebraic_foundations;Algebraic_kernel_d;Algebraic_kernel_for_circles;Algebraic_kernel_for_spheres;Alpha_shapes_2;Alpha_shapes_3;Apollonius_graph_2;Arithmetic_kernel;Arrangement_on_surface_2;BGL;Barycentric_coordinates_2;Boolean_set_operations_2;Bounding_volumes;Box_intersection_d;CGAL_Core;CGAL_ImageIO;CGAL_ipelets;Cartesian_kernel;Circular_kernel_2;Circular_kernel_3;Circulator;Combinatorial_map;Cone_spanners_2;Convex_decomposition_3;Convex_hull_2;Convex_hull_3;Convex_hull_d;Distance_2;Distance_3;Envelope_2;Envelope_3;Filtered_kernel;Generalized_map;Generator;Geomview;GraphicsView;HalfedgeDS;Hash_map;Homogeneous_kernel;Inscribed_areas;Installation;Interpolation;Intersections_2;Intersections_3;Interval_skip_list;Interval_support;Inventor;Jet_fitting_3;Kernel_23;Kernel_d;Kinetic_data_structures;Kinetic_framework;LEDA;Linear_cell_complex;MacOSX;Maintenance;Matrix_search;Mesh_2;Mesh_3;Mesher_level;Minkowski_sum_2;Minkowski_sum_3;Modifier;Modular_arithmetic;Nef_2;Nef_3;Nef_S2;NewKernel_d;Number_types;OpenNL;Operations_on_polyhedra;Optimal_transportation_reconstruction_2;Optimisation_basic;Partition_2;Periodic_2_triangulation_2;Periodic_3_triangulation_3;Point_set_2;Point_set_3;Point_set_processing_3;Point_set_shape_detection_3;Poisson_surface_reconstruction_3;Polygon;Polygon_mesh_processing;Polyhedron;Polyhedron_IO;Polyline_simplification_2;Polynomial;Polytope_distance_d;Principal_component_analysis;Principal_component_analysis_LGPL;Profiling_tools;Property_map;QP_solver;Random_numbers;Ridges_3;STL_Extension;Scale_space_reconstruction_3;Scripts;SearchStructures;Segment_Delaunay_graph_2;Segment_Delaunay_graph_Linf_2;Skin_surface_3;Snap_rounding_2;Solver_interface;Spatial_searching;Spatial_sorting;Straight_skeleton_2;Stream_lines_2;Stream_support;Subdivision_method_3;Surface_mesh;Surface_mesh_deformation;Surface_mesh_parameterization;Surface_mesh_segmentation;Surface_mesh_shortest_path;Surface_mesh_simplification;Surface_mesh_skeletonization;Surface_mesher;Sweep_line_2;TDS_2;TDS_3;Testsuite;Three;Triangulation;Triangulation_2;Triangulation_3;Union_find;Visibility_2;Voronoi_diagram_2;wininst
== Setting paths (DONE) ==

== Generate version files ==
-- CGAL_VERSION is 4.11-I-900
-- CGAL_VERSION_NR is 1041100900
-- CGAL_GIT_HASH is f346d279157d24e82e056e1fb82efc0de550af0d
-- CGAL_CREATED_SVN_REVISION is 99999 (dummy)
-- CGAL_MAJOR_VERSION=4
-- CGAL_MINOR_VERSION=11
-- CGAL_BUGFIX_VERSION=0
-- CGAL_BUILD_VERSION=900
-- CGAL_SONAME_VERSION=13
-- CGAL_SOVERSION     =13.0.1
-- CGAL_REFERENCE_CACHE_DIR=
-- Building shared libraries
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- USING CMake version: 3.12.2
-- System: Linux
-- USING GCC_VERSION = '5.4.0 20160609'
-- Using gcc version 4 or later. Adding -frounding-math
== Generate version files (DONE) ==

== Set up flags ==
-- Build type: Release
-- USING CXXFLAGS = '-std=c++11 -frounding-math -O3 -DNDEBUG'
-- USING LDFLAGS = ' '
== Set up flags (DONE) ==

== Detect external libraries ==
-- External libraries supported: GMP;GMPXX;MPFR;ZLIB;OpenGL;LEDA;MPFI;RS;RS3;OpenNL;Eigen3;BLAS;LAPACK;QGLViewer;ESBTL;Coin3D;NTL;IPE
-- Preconfiguring library: GMP ...
-- GMP has been preconfigured:
--   UseGMP-file:      
--   GMP include:      /usr/include/x86_64-linux-gnu
--   GMP libraries:    /usr/lib/x86_64-linux-gnu/libgmp.so
--   GMP definitions:  
-- USING GMP_VERSION = '6.1.0'
-- Preconfiguring library: MPFR ...
-- MPFR has been preconfigured:
--   UseMPFR-file:      
--   MPFR include:      /usr/include
--   MPFR libraries:    /usr/lib/x86_64-linux-gnu/libmpfr.so
--   MPFR definitions:  
-- USING MPFR_VERSION = '3.1.4'
-- __cplusplus is 201103
--   --> Do not link with Boost.Thread
-- Boost version: 1.58.0
-- Boost include:     /usr/include
-- Boost libraries:   
-- Boost definitions: 
-- USING BOOST_VERSION = '1.58.0'
== Detect external libraries (DONE) ==

== Write compiler_config.h ==
-- Performing Test CGAL_CFG_DENORMALS_COMPILE_BUG - Success
-- Performing Test CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG - Success
-- Performing Test CGAL_CFG_IEEE_754_BUG - Success
-- Performing Test CGAL_CFG_ISTREAM_INT_BUG - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_5 - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_6 - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_7 - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_8 - Success
-- Performing Test CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG - Success
-- Performing Test CGAL_CFG_NO_LIMITS - Success
-- Performing Test CGAL_CFG_NO_NEXTAFTER - Success
-- Performing Test CGAL_CFG_NO_STL - Success
-- Performing Test CGAL_CFG_NUMERIC_LIMITS_BUG - Success
-- Performing Test CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG - Success
-- Performing Test CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG - Success
-- Performing Test CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG - Success
-- Performing Test CGAL_CFG_USING_BASE_MEMBER_BUG_2 - Success
== Write compiler_config.h (DONE) ==

== Generating build files ==
Configuring libCGAL
-- Requested component: MPFR
-- Requested component: GMP
libCGAL is configured
-- Sources for CGAL component library 'CGAL_Core' detected
Configuring libCGAL_Core
-- Requested component: MPFR
-- Requested component: GMP
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
libCGAL_Core is configured
-- Sources for CGAL component library 'CGAL_ImageIO' detected
-- Sources for CGAL component library 'CGAL_Qt5' detected
-- Sources for CGAL component libraries 'CGAL_Core;CGAL_ImageIO;CGAL_Qt5' detected
== Generating build files (DONE) ==

-- Using local options file: /home/szx/PyMesh/third_party/geogram/CMakeOptions.txt
-- Configuring build for standalone Geogram (without Vorpaline)
-- GCC version >= 4.3, activating sign conversion warnings
-- GCC version >= 4.6, activating double promotion warnings
CMake Warning (dev) at build/CGALConfig.cmake:21 (include):
  Policy CMP0024 is not set: Disallow include export result.  Run "cmake
  --help-policy CMP0024" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  The file

    /home/szx/PyMesh/third_party/build/CGALExports.cmake

  was generated by the export() command.  It should not be used as the
  argument to the include() command.  Use ALIAS targets instead to refer to
  targets by alternative names.

Call Stack (most recent call first):
  cmake/TetWild.cmake:12 (FIND_PACKAGE)
  CMakeLists.txt:62 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build type: Release
-- USING CXXFLAGS = '-std=c++11 -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Code taken from Git branch: master
-- Requested component: Core
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Requested component: MPFR
-- Requested component: GMP
-- Configuring done
-- Generating done
-- Build files have been written to: /home/szx/PyMesh/third_party/build

**The third_party can build and install successfully with several warnings.**

**Then, I start work on build the PyMesh main section, here is the cmake result:**

`-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_LIBRARIES) 
CMake Warning (dev) at cmake/FindAllDependencies.cmake:14 (FIND_PACKAGE):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /home/szx/PyMesh/python/pymesh/third_party/

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  Settings.cmake:21 (FIND_PACKAGE)
  CMakeLists.txt:5 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- BSP library cannot be found.  Consider set BSP_PATH environment variable (missing: BSP_INCLUDE_DIRS BSP_LIBRARIES) 
-- A library with LAPACK API found.
-- OpenMP found
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/szx/PyMesh/build
`
**Then I do make, got the errors:**
[ 70%] Building CXX object tools/Wires/CMakeFiles/lib_Wires.dir/Misc/BoundaryRemesher.cpp.o
/home/szx/PyMesh/tools/Wires/Misc/BoundaryRemesher.cpp: In function ‘void BoundaryRemsherHelper::triangulate(PyMesh::MatrixFr, PyMesh::MatrixIr, PyMesh::MatrixFr&, PyMesh::MatrixIr&, PyMesh::Float)’:
/home/szx/PyMesh/tools/Wires/Misc/BoundaryRemesher.cpp:27:9: error: ‘TriangleWrapper’ was not declared in this scope
         TriangleWrapper triangle;
         ^
/home/szx/PyMesh/tools/Wires/Misc/BoundaryRemesher.cpp:28:9: error: ‘triangle’ was not declared in this scope
         triangle.set_points(vertices);
         ^
tools/Wires/CMakeFiles/lib_Wires.dir/build.make:348: recipe for target 'tools/Wires/CMakeFiles/lib_Wires.dir/Misc/BoundaryRemesher.cpp.o' failed
make[2]: *** [tools/Wires/CMakeFiles/lib_Wires.dir/Misc/BoundaryRemesher.cpp.o] Error 1
CMakeFiles/Makefile2:2014: recipe for target 'tools/Wires/CMakeFiles/lib_Wires.dir/all' failed
make[1]: *** [tools/Wires/CMakeFiles/lib_Wires.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Any comment is appreciated.**

**Comment by neoglez** [comment]
I was having the same problem. Installing the triangle dependency solved it...but another problems appear. You can give it a try though.

**Comment by szx0112** [comment]
Thanks for the reply. I did got another error after that, and cannot go back to this again ....
