### ISSUE TITLE
fatal error: unsupported/Eigen/SparseExtra: on Ubuntu 18.04

### ISSUE THREAD

**Issue by gulib** [PyMesh/PyMesh#124]
Hello,

I was trying to install pymesh in my Ubuntu 18.04, but having the following error with cmake

```
CMake Error in tests/tools/Compression/CMakeLists.txt:
  Imported target "PyMesh::UnitTest" includes non-existent path

    "/usr/include/unsupported"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
but generation and building the files are done. But when I am trying to make, having the following error

> In file included from /home/galib/PyMesh/third_party/libigl/include/igl/slice.h:84:0,
>                  from /home/galib/PyMesh/third_party/libigl/include/igl/remove_unreferenced.cpp:9,
>                  from /home/galib/PyMesh/third_party/libigl/include/igl/remove_unreferenced.h:79,
>                  from /home/galib/PyMesh/tools/IGL/CellPartition.cpp:10:
> /home/galib/PyMesh/third_party/libigl/include/igl/slice.cpp:12:10: fatal error: unsupported/Eigen/SparseExtra: No such file or directory
>  #include <unsupported/Eigen/SparseExtra>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Can anyone help me to solve the problem?

Regards,
Asad

**Comment by qnzhou** [comment]
Did you encounter this error while building `third_party` libraries?

**Comment by qnzhou** [comment]
Can you check eigen is found correctly with the following command?

```
 grep -i eigen $PYMESH_PATH/build/CMakeCache.txt
```

The `EIGEN_INCLUDE_DIRS` should points to something like `$PYMESH_PATH/python/pymesh/third_party/include/eigen3`

**Comment by gulib** [comment]
I ran this command
`grep -i eigen PyMesh/build/CMakeCache.txt`

and the output i get

```
//The directory where Eigen/Core resides
EIGEN_INCLUDE_DIRS:PATH=/usr/include
//ADVANCED property for variable: EIGEN_INCLUDE_DIRS
EIGEN_INCLUDE_DIRS-ADVANCED:INTERNAL=1
//Details about finding Eigen
FIND_PACKAGE_MESSAGE_DETAILS_Eigen:INTERNAL=[/usr/include][v()]
```
I checked the `PyMesh/python/pymesh/third_party/include` directory and its empty

**Comment by qnzhou** [comment]
It think you may have forgot to run `make install` from the `$PYMESH_PATH/third_party/build` directory?

**Comment by gulib** [comment]
Yes!!!! You are right..... Thank You very much.....
