### ISSUE TITLE
ImportError: No module named pymesh

### ISSUE THREAD

**Issue by zeal-github** [PyMesh/PyMesh#128]
Hi, I was trying to install pymesh by this tutorial https://pymesh.readthedocs.io/en/latest/installation.html.
Everything went right, but went to the last step, 
`python -c "import pymesh; pymesh.test()"`, 
when I in directory `~/PyMesh/`, it report `ImportError: No module named pymesh`.
However, when I go into the directory `~/PyMesh/python/`, everything goes right, the test report OK, and I can start python and import pymesh.
I was installing by conda environment.
What's the solution to it? It's that system path problem?

**Comment by qnzhou** [comment]
It seems pymesh is not installed correctly.  Did you run `python setup.py install` or `python setup.py install --user`?

**Comment by zeal-github** [comment]
@qnzhou Yes, I run sudo python setup.py install. I found that pymesh was installed in `/usr/local/lib/python2.7/dist-packages/`, but I'm using conda to manage my environment and packages.
I think I should compile the source code using `cmake, make`, and change the install path. I'm trying to figure out how to use `cmake`, can you give me some advice? Or maybe it's other problem?

**Comment by zeal-github** [comment]
@qnzhou 
I think I have found the solution. 
`./setup.py install` use `/usr/bin/env python` as the default interpreter. When using conda environment, you just need to replace the first line in `setup.py`:#!/usr/bin/env python as `#!/home/path/to/anaconda$version/envs/py2.7/bin/python2.7` (change according to your env path).
Also, it work find to python2.7 but not python 3.6.
I hope you can add some illustration when using anaconda in the installation tutorial.

**Comment by qnzhou** [comment]
Thanks for the clarification.  Typically, the name `python` is redefined in virtual environment, thus `/usr/bin/env python` normally works.  Another solution is to run `python ./setup.py install` where one can replace python with the specific python version wanted.
