### ISSUE TITLE
Docker Image error

### ISSUE THREAD

**Issue by marcovolino** [PyMesh/PyMesh#134]
I think there is an error with the dockerfile due to a very recent change caused by an update to libigl
See https://libigl.github.io/rewritten-history/

I get the following error when building using docker:
error: Server does not allow request for unadvertised object 274dc2de4535e7a91aac782d088c0ee14c6d3f1e
Fetched in submodule path 'third_party/libigl', but it did not contain 274dc2de4535e7a91aac782d088c0ee14c6d3f1e. Direct fetching of that commit failed.

**Comment by qnzhou** [comment]
I have updated my fork of libigl.  It should work fine now.  Can you check that?
