### ISSUE TITLE
CGAL Sphere takes _squared_ radius as input parameter to constructor

### ISSUE THREAD

**Issue by alecjacobson** [PyMesh/PyMesh#146]
https://github.com/PyMesh/PyMesh/blob/d5465939728851744af9ed078253d31529100952/tools/Tetrahedralization/CGAL/CGALMeshDomain.h#L213

https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Sphere__3.html

Might not actually matter if input is always rescaled to unit sphere, but caused me a bug when I tried to copy paste this code ; -)

**Comment by qnzhou** [comment]
Thanks Alec, good catch!
