### ISSUE TITLE
Installation problem on CentOS

### ISSUE THREAD

**Issue by uray10** [PyMesh/PyMesh#159]
I am building PyMesh with CMake on an Intel Skylake Silver running CentOS.

I am able to execute `cmake ..` but whenever I execute `make`, I get the following errors:

`/home/uray/PyMesh/third_party/jigsaw/src/libcpp/containers/priorityset.hpp:379:29: error: 'void_type containers::priorityset<D, P, A, C>::_pop_root(containers::priorityset<D, P, A, C>::data_type&) [with D = geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist; P = geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_pred; A = allocators::basic_alloc; C = containers::array<geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist, allocators::basic_alloc>; void_type = void; containers::priorityset<D, P, A, C>::data_type = geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist]', declared using local type 'containers::priorityset<geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist, geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_pred, allocators::basic_alloc, containers::array<geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist, allocators::basic_alloc> >::data_type {aka geom_tree::aabb_tree<I, K, N, A>::near(geom_tree::aabb_tree<I, K, N, A>::real_type*, geom_tree::aabb_tree<I, K, N, A>::item_data*&) [with I = geom_tree::aabb_item_rect_k<double, int, 3ul>; long unsigned int K = 3ul; N = geom_tree::aabb_node_base_k; A = allocators::basic_alloc; bool_type = bool; geom_tree::aabb_tree<I, K, N, A>::real_type = double; geom_tree::aabb_tree<I, K, N, A>::item_data = containers::single_item<geom_tree::aabb_item_rect_k<double, int, 3ul> >]::node_dist}', is used but never defined [-fpermissive]
     __inline_call void_type _pop_root (` 

I get the above error at the absolute end of `make`, before it exits. This is the error which I get at the absolute start of `make`:

`[  0%] Building CXX object CMakeFiles/jigsaw.dir/jigsaw/src/jigsaw.cpp.o
In file included from /home/uray/PyMesh/third_party/jigsaw/src/libcpp/allocators.hpp:55:0,
                 from /home/uray/PyMesh/third_party/jigsaw/src/libcpp/containers.hpp:49,
                 from /home/uray/PyMesh/third_party/jigsaw/src/libcpp/rdelmesh.hpp:61,
                 from /home/uray/PyMesh/third_party/jigsaw/src/jigsaw.cpp:233:
/home/uray/PyMesh/third_party/jigsaw/src/libcpp/allocators/alloc_item.hpp:525:5: error: 'is_trivially_copyable' is not a member of 'std'
     std::is_trivially_copyable <D>::value >`

There are many more errors while running `make`. All of the same type. I am not sure how to fix this. Any help would be appreciated.

**Comment by qnzhou** [comment]
It seems your compiler does not support modern C++.  Can you check the version of your compiler?  E.g.
```
g++ -v
```

**Comment by uray10** [comment]
`g++ -v` gives me this output:

`Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/ohpc/pub/compiler/gcc/5.4.0/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --disable-multilib --enable-languages=c,c++,fortran --prefix=/opt/ohpc/pub/compiler/gcc/5.4.0
Thread model: posix
gcc version 5.4.0 (GCC)`

**Comment by uray10** [comment]
For some reason my compiler was picking up an old version of GCC instead of the current latest version. Explicitly pointing to the current version solved the problem
