### ISSUE TITLE
Gaussian curvature not returning any results

### ISSUE THREAD

**Issue by AAcquier** [PyMesh/PyMesh#160]
Hi,
I am trying to determine the Gaussian curvature on a part of the face called the nassau labial furrow (trench which appears on the top corner of the lips when smiling) from data generated from a kinect but it returns nothing when the attribute is called. Do to the mesh, I am using the **wires.WireNetwork.create_from_data** function of pymesh, the data points in meters that feeding it are under the form:
> [[-0.01929285  0.15076235  0.29188313]
>  [-0.02161789  0.15406285  0.29776372]
>  [-0.01936876  0.15352987  0.29500153]]

and the edges are found using the scipy Delaunay technique as follow:

> tri = Delaunay(depth_tuple_list) 
>    simplices =  tri.simplices
>    edge= set()
>    for s in simplices:
>         edge.add((s[0], s[1]))
>         edge.add((s[0], s[2]))
>         edge.add((s[0], s[3]))
>   edge_list=np.array(list(edge))

The wire mesh is generated:

> p1_wire_network = pymesh.wires.WireNetwork.create_from_data (depth_tuple_list, edge_list)
> print p1_wire_network.dim, p1_wire_network.num_vertices, p1_wire_network.num_edges

The print statement more or less returns (last reading fluctuates depending how close I am from the kinect):
> (3L, 741L, 4313L)

Finally the Gaussian curvature is set:

> p1_wire_network.add_attribute("vertex_gaussian_curvature")
> gauss = p1_wire_network.get_attribute("vertex_gaussian_curvature")
> print gauss

Which return an empty array and no error message, I am not really sure I am doing wrong. Does the wires class support the Gaussian curvatures? If not is there one class that support it and that also support the meshing of unclosed surface?

**Comment by qnzhou** [comment]
The problem is that you are creating a wire network instead of a mesh.  A wire network does not have the concept of a face, thus it does not represent a surface.  Instead, it represents a number of nodes and the edges connecting them, thus Gaussian curvature is not defined here.

You need to create a mesh instead.  E.g. `mesh = pymesh.form_mesh(depth_tuple_list, tri.simplices)`.

**Comment by AAcquier** [comment]
Thanks I got a Gaussian curvature but the output is not what I expected, from the code:
   

>  tri = ConvexHull(depth_tuple_list)
>     p1_wire_network = pymesh.form_mesh (depth_tuple_list, tri.simplices)
>     p1_wire_network.add_attribute("vertex_gaussian_curvature")
>     gauss = p1_wire_network.get_attribute("vertex_gaussian_curvature")
>      print "gauss"
>     print gauss

I get this kind of output:

> gauss
> [5.90721804e-02 9.94393740e-05            inf            inf
>             inf            inf            inf 7.95248981e-04
>             inf            inf            inf            inf
>             inf            inf 3.04647203e-02 1.13617126e-02
>  2.17217723e-03            inf 9.37130020e-07            inf
>  2.86896361e-03 1.59642551e-03 3.96152584e-02            inf
>  9.34981506e-03            inf            inf            inf
>             inf            inf            inf            inf
>             inf 2.40057073e-03 9.02166283e-04            inf
>  1.87691502e-03            inf            inf            inf  ]

What are those infinity value mean? does that mean the Gaussian curvature equal 0?

**Comment by qnzhou** [comment]
That looks like numerical problems in the Gaussian curvature computation (likely divide by 0).  I suspect that your input geometry contains degenerate triangles.  You can try check for degeneracies using:

```python
r = pymesh.get_degenerated_faces(p1_wire_network);  # by the way, p1_wire_network should be renamed to p1_mesh
prrint(r)
```

You can also resolve all degeneracies using

```python
p1_wire_network, info = pymesh.remove_degenerated_triangles(p1_wire_network);
```

If these do not help, is it possible to share the model with me?  You can save the model by

```python
pymesh.save_mesh("to_debbug.obj", p1_wire_network)
```

**Comment by AAcquier** [comment]
Thanks Qingnan,

 I got it working by using the :

> pymesh.remove_degenerated_triangles(p1_mesh)

even though the:

> pymesh.get_degenerated_faces(p1_mesh)

did not return anything.
