### ISSUE TITLE
Number of slices mismatch

### ISSUE THREAD

**Issue by jorgal** [PyMesh/PyMesh#166]
I wonder why when I run this test script, I get an output with a wrong number of slices for certain meshes. (specifically with LowPolyTri.obj). I am attaching the script and .obj input files

import numpy as np
import pymesh

mesh_1 = pymesh.load_mesh("icosphere.obj")
mesh_2 = pymesh.load_mesh("LowPolyTri.obj")

direction = np.array([0.0, 1.0, 0.0])
num_slices = 10

print(mesh_1.num_vertices, mesh_1.num_faces, mesh_1.num_voxels)
print(mesh_1.dim, mesh_1.vertex_per_face, mesh_1.vertex_per_voxel)
slice_list_1 = pymesh.slice_mesh(mesh_1, direction, num_slices)
print('cross_sections:', len(slice_list_1))
print()
print(mesh_2.num_vertices, mesh_2.num_faces, mesh_2.num_voxels)
print(mesh_2.dim, mesh_2.vertex_per_face, mesh_2.vertex_per_voxel)
slice_list_2 = pymesh.slice_mesh(mesh_2, direction, num_slices)
print('cross_sections:', len(slice_list_2))

Output:

10242 20480 0
3 3 0
cross_sections: 10

4944 9884 0
3 3 0
cross_sections: 24

Process finished with exit code 0

[models.tar.gz](https://github.com/PyMesh/PyMesh/files/2974457/models.tar.gz)
[script.tar.gz](https://github.com/PyMesh/PyMesh/files/2974458/script.tar.gz)

**Comment by qnzhou** [comment]
@jorgal Thanks for reporting this.  I think it should have been fixed now.  Can you try again?

**Comment by jorgal** [comment]
I have updated PyMesh and tried again. Everything is ok now. Thank you very
much.
Best regards
