### ISSUE TITLE
What is mean curvature neighborhood size?

### ISSUE THREAD

**Issue by spk921** [PyMesh/PyMesh#167]
Here it seems using the mesh.get_dim() as neighborhood size. 
Then is it 3? and just using adjacent vertices for the calculation? 
https://github.com/PyMesh/PyMesh/blob/master/src/Attributes/VertexMeanCurvatureAttribute.cpp#L26

**Comment by qnzhou** [comment]
`dim` is _not_ the neighborhood side, it is the dimension of the mesh, which is also the dimension of the Laplacian vector (which is computed based on the 1-ring neighborhood of a vertex).

See [here](http://graphics.stanford.edu/courses/cs468-10-fall/LectureSlides/05_Diff_Geo.pdf) (towards the end) for references on mean curvature computation.

**Comment by spk921** [comment]
@qnzhou  Thank you very much for the answer. Would like to verify my understanding, then what is the dimension of the mesh? Is it a number of the verticies or faces or (x,y,z) 3 Cartesian coordinates? And the library uses 1-ring neighborhood for the curvature calculation. Am I correct?

**Comment by qnzhou** [comment]
Dimension 3 means the mesh is embedded in R^3 space, i.e. each vertex has three coordinates.

And yes, the discrete mean curvature is computed using 1-ring neighborhood.

**Comment by spk921** [comment]
Thank you for the comments.
