### ISSUE TITLE
issue installing 

### ISSUE THREAD

**Issue by sara17585** [PyMesh/PyMesh#173]
Hi all, 

I followed all the instructure and installed PyMesh but  when I import pymesh it seems it can not find the packages:
>>> import pymesh
>>> pymesh.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pymesh' has no attribute 'test'
>>> 

Do you know what I missed ?

**Comment by Karltlbm** [comment]
How did you resolve the issue ?

**Comment by sara17585** [comment]
I don’t remember exactly, but I think I had made some mistake while installing pymesh. I reinstalled it and the problem was gone
