### ISSUE TITLE
git submodule update --init fails

### ISSUE THREAD

**Issue by paulhankin-vrbn** [PyMesh/PyMesh#174]
Building pymesh in a dockerfile fails with problems when running git submodule init:

I see changes submitted 15h ago to the geogram submodule, so I guess it broke something...

Here's the failure message:
Submodule path 'third_party/fmt': checked out '355eb6d29ad7dbcb017420442af237e3cf6d8054'
error: Server does not allow request for unadvertised object a064cd2e26eeb3ef6375e0ad2d7792d58468fe7e
Fetched in submodule path 'third_party/geogram', but it did not contain a064cd2e26eeb3ef6375e0ad2d7792d58468fe7e. Direct fetching of that commit failed.
The command '/bin/sh -c git clone https://github.com/PyMesh/PyMesh.git &&       cd PyMesh &&    git submodule update --init' returned a non-zero code: 1

Here's the full git command with output:

RUN git clone https://github.com/PyMesh/PyMesh.git &&        cd PyMesh &&    git submodule update --init
 ---> Running in XXXX
Cloning into 'PyMesh'...
Submodule 'third_party/Clipper' (https://github.com/PyMesh/Clipper.git) registered for path 'third_party/Clipper'
Submodule 'third_party/TetWild' (https://github.com/PyMesh/TetWild.git) registered for path 'third_party/TetWild'
Submodule 'third_party/WindingNumber' (https://github.com/PyMesh/WindingNumber.git) registered for path 'third_party/WindingNumber'
Submodule 'third_party/carve' (https://github.com/PyMesh/carve.git) registered for path 'third_party/carve'
Submodule 'third_party/cgal' (https://github.com/PyMesh/cgal.git) registered for path 'third_party/cgal'
Submodule 'third_party/cork' (https://github.com/PyMesh/cork.git) registered for path 'third_party/cork'
Submodule 'third_party/draco' (https://github.com/PyMesh/draco.git) registered for path 'third_party/draco'
Submodule 'third_party/eigen' (https://github.com/PyMesh/eigen.git) registered for path 'third_party/eigen'
Submodule 'third_party/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'third_party/fmt'
Submodule 'third_party/geogram' (https://github.com/PyMesh/geogram.git) registered for path 'third_party/geogram'
Submodule 'third_party/jigsaw' (https://github.com/PyMesh/jigsaw.git) registered for path 'third_party/jigsaw'
Submodule 'libigl' (https://github.com/PyMesh/libigl.git) registered for path 'third_party/libigl'
Submodule 'third_party/mmg' (https://github.com/PyMesh/mmg.git) registered for path 'third_party/mmg'
Submodule 'third_party/pybind11' (https://github.com/PyMesh/pybind11.git) registered for path 'third_party/pybind11'
Submodule 'third_party/qhull' (https://github.com/PyMesh/qhull.git) registered for path 'third_party/qhull'
Submodule 'third_party/quartet' (https://github.com/PyMesh/quartet.git) registered for path 'third_party/quartet'
Submodule 'third_party/spdlog' (https://github.com/gabime/spdlog.git) registered for path 'third_party/spdlog'
Submodule 'third_party/tbb' (https://github.com/PyMesh/tbb.git) registered for path 'third_party/tbb'
Submodule 'third_party/tetgen' (https://github.com/PyMesh/tetgen.git) registered for path 'third_party/tetgen'
Submodule 'third_party/triangle' (https://github.com/PyMesh/triangle.git) registered for path 'third_party/triangle'
Cloning into '/PyMesh/third_party/Clipper'...
Cloning into '/PyMesh/third_party/TetWild'...
Cloning into '/PyMesh/third_party/WindingNumber'...
Cloning into '/PyMesh/third_party/carve'...
Cloning into '/PyMesh/third_party/cgal'...
Cloning into '/PyMesh/third_party/cork'...
Cloning into '/PyMesh/third_party/draco'...
Cloning into '/PyMesh/third_party/eigen'...
Cloning into '/PyMesh/third_party/fmt'...
Cloning into '/PyMesh/third_party/geogram'...
Cloning into '/PyMesh/third_party/jigsaw'...
Cloning into '/PyMesh/third_party/libigl'...
Cloning into '/PyMesh/third_party/mmg'...
Cloning into '/PyMesh/third_party/pybind11'...
Cloning into '/PyMesh/third_party/qhull'...
Cloning into '/PyMesh/third_party/quartet'...
Cloning into '/PyMesh/third_party/spdlog'...
Cloning into '/PyMesh/third_party/tbb'...
Cloning into '/PyMesh/third_party/tetgen'...
Cloning into '/PyMesh/third_party/triangle'...
Submodule path 'third_party/Clipper': checked out '3fd3457741d275b887ad16abacccbd01eda2175c'
Submodule path 'third_party/TetWild': checked out '5b0f81552fbd66c1ed66168fd7bbf222e3391816'
Submodule path 'third_party/WindingNumber': checked out 'e011b7bc9fa1e2570651097936ccf2314fdcbe86'
Submodule path 'third_party/carve': checked out 'd328ad2136a4fa6413db8ad264ed219095bb6744'
Submodule path 'third_party/cgal': checked out '052a8313451e5ea1d4d53ff0145958909f57d42f'
Submodule path 'third_party/cork': checked out '360820dd981fa72117f255ddaa68367419f7526c'
Submodule path 'third_party/draco': checked out '063994c362871d6f149c24c669122e4ef3fa8196'
Submodule path 'third_party/eigen': checked out 'ed3db99ec3caff039f72645b7c5feb68717c8655'
Submodule path 'third_party/fmt': checked out '355eb6d29ad7dbcb017420442af237e3cf6d8054'
error: Server does not allow request for unadvertised object a064cd2e26eeb3ef6375e0ad2d7792d58468fe7e
Fetched in submodule path 'third_party/geogram', but it did not contain a064cd2e26eeb3ef6375e0ad2d7792d58468fe7e. Direct fetching of that commit failed.
The command '/bin/sh -c git clone https://github.com/PyMesh/PyMesh.git &&       cd PyMesh &&    git submodule update --init' returned a non-zero code: 1

**Comment by qnzhou** [comment]
I have updated master branch.  Can you give it a try again?

**Comment by paulhankin-vrbn** [comment]
Thanks! Whatever you did worked -- it now successfully finishes the git command.
