### ISSUE TITLE
create mesh by datas

### ISSUE THREAD

**Issue by guozhaojian** [PyMesh/PyMesh#177]
I was a new user for ros, and try to use the pointcloud data to create mesh and save in .ply file.

When i see the guide in the https://pymesh.readthedocs.io/en/latest/,  in the example, always use
"mesh = pymesh.load_mesh("cube.obj"); " to load the mesh. 
And what should i do to create the mesh with the pointcloud data or with the x,y,z points.

**Comment by qnzhou** [comment]
You can use `pymesh.form_mesh` to load from data.  See https://pymesh.readthedocs.io/en/latest/basic.html#loading-mesh

**Comment by guozhaojian** [comment]
> You can use `pymesh.form_mesh` to load from data. See https://pymesh.readthedocs.io/en/latest/basic.html#loading-mesh

when make the source code, make tests failed.
and log:
[----------] Global test environment tear-down
[==========] 224 tests from 51 test cases ran. (658 ms total)
[  PASSED  ] 223 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FaceAreaAttributeTest.3D_tet

 1 FAILED TEST
tests/src/CMakeFiles/run_Mesh_tests.dir/build.make:57: recipe for target 'tests/src/CMakeFiles/run_Mesh_tests' failed
make[3]: *** [tests/src/CMakeFiles/run_Mesh_tests] Error 1
CMakeFiles/Makefile2:2548: recipe for target 'tests/src/CMakeFiles/run_Mesh_tests.dir/all' failed
make[2]: *** [tests/src/CMakeFiles/run_Mesh_tests.dir/all] Error 2
CMakeFiles/Makefile2:2337: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
Makefile:391: recipe for target 'tests' failed
make: *** [tests] Error 2

**Comment by guozhaojian** [comment]
兄弟，我尝试完了很多种安装方式，还是不成功。
我溜了，

**Comment by qnzhou** [comment]
Sorry to hear that. :(

**Comment by hysoka79** [comment]
@qnzhou First of all thanks to the code.:)) But I meet the problem above. Is there any solution??
