### ISSUE TITLE
Boolean operation: Attribute "source" does not exist

### ISSUE THREAD

**Issue by MMManuel** [PyMesh/PyMesh#190]
Hello,
I have a problem with the **boolean operation**
In general I want to slice my object with the function `pymesh.slice_mesh(mesh, direction, N)`
Here the code snippet:
```
mesh1 = pymesh.load_mesh("Model/wall.stl")
threeD_mesh1=pymesh.tetrahedralize(mesh1,cell_size=20,with_timing=True)[0]
sliced_mesh= pymesh.slice_mesh(threeD_mesh,np.array([0,0,1]),10)
```
I get an _**RuntimeError: Attribute "source" does not exist.**_ in the file _slice_mesh.py_ because the boolean operation don't get any _**face_sources**_
In the file _boolean.py_ the _face_source_ is always 0 and therefore the attribute source is not added
```
    if len(face_sources) != 0:
        output_mesh.add_attribute("source_face");
        output_mesh.set_attribute("source_face", face_sources);
        output_mesh.add_attribute("source");
        sources = face_sources < mesh_1.num_faces;
        output_mesh.set_attribute("source", sources);
```
I reduced the problem to the boolean operation as described in the documentation
```
mesh1 = pymesh.load_mesh("Model/wall.ply")
mesh2 = pymesh.load_mesh("Model/hole.ply")
output_mesh = pymesh.boolean(mesh1, mesh2,operation="union",engine="igl")
output_mesh.get_attribute("source")
```
But I also get the error _**RuntimeError: Attribute "source" does not exist.**_ 
What can cause the problem?

**Comment by qnzhou** [comment]
Have you tried slicing the surface mesh?  (i.e. without generating a tet mesh):

```python
mesh1 = pymesh.load_mesh("Model/wall.stl")
sliced_mesh= pymesh.slice_mesh(mesh1,np.array([0,0,1]),10)
```
