### ISSUE TITLE
Error during installation: no member named '_mp_size'

### ISSUE THREAD

**Issue by jasiozaucha** [PyMesh/PyMesh#205]
18 errors generated.
make[2]: *** [tools/IGL/CMakeFiles/lib_IGL.dir/CellPartition.cpp.o] Error 1
make[1]: *** [tools/IGL/CMakeFiles/lib_IGL.dir/all] Error 2
make: *** [all] Error 2

All of the error regard '_mp_size' for example:
/opt/local/include/boost/multiprecision/gmp.hpp:1653:11: error: no member named '_mp_size' in '__mpz_struct'

**Comment by HaominIsMe** [comment]
I got the same problem

**Comment by Cascades** [comment]
What compiler and version are you using? Are you running CMake by hand or the setup.py script?

**Comment by zfergus** [comment]
I have the same issue (see full output [here](https://github.com/PyMesh/PyMesh/files/3752928/Pymesh-error.txt)). I am using macOS 10.15 with `Apple clang version 11.0.0 (clang-1100.0.33.8)`. This is while compiling with CMake by hand.

I have been experiencing this problem for a while (including while using macOS 10.14). I found a similar issue here: https://github.com/boostorg/multiprecision/issues/158. Which claims it is a Clang bug (https://bugs.llvm.org/show_bug.cgi?id=43266). I was hoping an update would fix it, but no such luck.

**Comment by qnzhou** [comment]
This issue should be resolved.  Please checkout the latest code.
