### ISSUE TITLE
submodule update --init error: Server does not allow request for unadvertised object (third party/libigl)

### ISSUE THREAD

**Issue by filipkorf** [PyMesh/PyMesh#218]
Hi,
I am trying to install PyMesh and I am getting an error while running submodule update --init,  can you help me please?  It fails while fetching in submodule path 'third_party/libigl'

The error:
`error: Server does not allow request for unadvertised object e699d257fe860d4fd82709835e72438bd0cd1533
Fetched in submodule path 'third_party/libigl', but it did not contain e699d257fe860d4fd82709835e72438bd0cd1533. Direct fetching of that commit failed.
`

Here is the terminal output:

`$ git submodule update --init
Submodule 'third_party/Clipper' (https://github.com/PyMesh/Clipper.git) registered for path 'third_party/Clipper'
Submodule 'third_party/TetWild' (https://github.com/PyMesh/TetWild.git) registered for path 'third_party/TetWild'
Submodule 'third_party/WindingNumber' (https://github.com/PyMesh/WindingNumber.git) registered for path 'third_party/WindingNumber'
Submodule 'third_party/carve' (https://github.com/PyMesh/carve.git) registered for path 'third_party/carve'
Submodule 'third_party/cgal' (https://github.com/PyMesh/cgal.git) registered for path 'third_party/cgal'
Submodule 'third_party/cork' (https://github.com/PyMesh/cork.git) registered for path 'third_party/cork'
Submodule 'third_party/draco' (https://github.com/PyMesh/draco.git) registered for path 'third_party/draco'
Submodule 'third_party/eigen' (https://github.com/PyMesh/eigen.git) registered for path 'third_party/eigen'
Submodule 'third_party/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'third_party/fmt'
Submodule 'third_party/geogram' (https://github.com/PyMesh/geogram.git) registered for path 'third_party/geogram'
Submodule 'third_party/jigsaw' (https://github.com/PyMesh/jigsaw.git) registered for path 'third_party/jigsaw'
Submodule 'libigl' (https://github.com/PyMesh/libigl.git) registered for path 'third_party/libigl'
Submodule 'third_party/mmg' (https://github.com/PyMesh/mmg.git) registered for path 'third_party/mmg'
Submodule 'third_party/pybind11' (https://github.com/PyMesh/pybind11.git) registered for path 'third_party/pybind11'
Submodule 'third_party/qhull' (https://github.com/PyMesh/qhull.git) registered for path 'third_party/qhull'
Submodule 'third_party/quartet' (https://github.com/PyMesh/quartet.git) registered for path 'third_party/quartet'
Submodule 'third_party/spdlog' (https://github.com/gabime/spdlog.git) registered for path 'third_party/spdlog'
Submodule 'third_party/tbb' (https://github.com/PyMesh/tbb.git) registered for path 'third_party/tbb'
Submodule 'third_party/tetgen' (https://github.com/PyMesh/tetgen.git) registered for path 'third_party/tetgen'
Submodule 'third_party/triangle' (https://github.com/PyMesh/triangle.git) registered for path 'third_party/triangle'
Cloning into '/home/martin/zkouska2/PyMesh/third_party/Clipper'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/TetWild'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/WindingNumber'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/carve'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/cgal'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/cork'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/draco'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/eigen'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/fmt'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/geogram'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/jigsaw'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/libigl'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/mmg'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/pybind11'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/qhull'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/quartet'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/spdlog'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/tbb'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/tetgen'...
Cloning into '/home/martin/zkouska2/PyMesh/third_party/triangle'...
Submodule path 'third_party/Clipper': checked out '3fd3457741d275b887ad16abacccbd01eda2175c'
Submodule path 'third_party/TetWild': checked out '5b0f81552fbd66c1ed66168fd7bbf222e3391816'
Submodule path 'third_party/WindingNumber': checked out 'e011b7bc9fa1e2570651097936ccf2314fdcbe86'
Submodule path 'third_party/carve': checked out 'd328ad2136a4fa6413db8ad264ed219095bb6744'
Submodule path 'third_party/cgal': checked out '1e3d2e450be9c8dce65ff28859a956691a8c2bb4'
Submodule path 'third_party/cork': checked out '360820dd981fa72117f255ddaa68367419f7526c'
Submodule path 'third_party/draco': checked out '063994c362871d6f149c24c669122e4ef3fa8196'
Submodule path 'third_party/eigen': checked out 'ed3db99ec3caff039f72645b7c5feb68717c8655'
Submodule path 'third_party/fmt': checked out '355eb6d29ad7dbcb017420442af237e3cf6d8054'
Submodule path 'third_party/geogram': checked out '25228ad2a88b793fc8de651ecf6ca7ee76819d5a'
Submodule path 'third_party/jigsaw': checked out '9c677b58234c64e2586e361d53bf60ce7e4ed3bb'
error: Server does not allow request for unadvertised object e699d257fe860d4fd82709835e72438bd0cd1533
Fetched in submodule path 'third_party/libigl', but it did not contain e699d257fe860d4fd82709835e72438bd0cd1533. Direct fetching of that commit failed.
`

**Comment by edwardwang1** [comment]
Hi,


I followed the instructions found at this link:
https://github.com/AppImage/AppImageKit/issues/511

The command that worked for me was
git submodule update --depth 500

**Comment by filipkorf** [comment]
Thank you kindly for your advice @edwardwang1, it helped :+1: 

but I am a newbie and I encountered another error farther in the installation, can you please help again (or anybody else)

while building pymesh library with `make` in $PYMESH_PATH/build it goes fine untill 55% and then I get an error that says 

"‘TriangleWrapper’ was not declared in this scope"

I found similar issues here, but I don't understand them very well:
https://github.com/PyMesh/PyMesh/issues/73#issue-296016448
https://github.com/PyMesh/PyMesh/issues/121#issue-359979691


The error:
...
[ 55%] Building CXX object tools/Boolean/CMakeFiles/lib_Boolean.dir/Clipper/ClipperEngine.cpp.o
$PYMESH_PATH/tools/Boolean/Clipper/ClipperEngine.cpp: In member function ‘void PyMesh::ClipperEngine::extract_result(const Paths&)’:
$PYMESH_PATH/tools/Boolean/Clipper/ClipperEngine.cpp:214:9: error: ‘TriangleWrapper’ was not declared in this scope
  214 |         TriangleWrapper tri_wrapper;
      |         ^~~~~~~~~~~~~~~
$PYMESH_PATH/tools/Boolean/Clipper/ClipperEngine.cpp:215:9: error: ‘tri_wrapper’ was not declared in this scope
  215 |         tri_wrapper.set_points(loop_vertices);
      |         ^~~~~~~~~~~
make[2]: *** [tools/Boolean/CMakeFiles/lib_Boolean.dir/build.make:102: tools/Boolean/CMakeFiles/lib_Boolean.dir/Clipper/ClipperEngine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:995: tools/Boolean/CMakeFiles/lib_Boolean.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

(I used $PYMESH_PATH here as used in the instructions for my path to pymesh)

**Comment by edwardwang1** [comment]
Hi,

I actually ran into the same issue as well. I tried a lot of options and eventually got PyMesh to work, but I'm not sure which ones did the trick so I will list them all here. For reference, I am running Ubuntu 18.04LTS and Cmake 3.16.1

I followed the instructions here: https://github.com/PyMesh/PyMesh/issues/168
to uninstall Python 2, and download the dependencies.

Then I deleted my PyMesh directory, and recloned it from github. I used the:
 `git submodule update --init` command, and for some reason I didn't need to add the depth flag.

After that, when I tried building the dependencies by following the instructions, everything worked.

**Comment by qnzhou** [comment]
I have updated some of the submodules.  Please `git pull` and `git submodule update --init` again.

Another update is that I have remove the single `CMakeLists.txt` for the third party dependencies.  Using `setup.py build` should build both third party dependencies as well as the main project.

**Comment by filipkorf** [comment]
Hi guys, sorry for the late reply, you both rock! It helped me a ton, it is working, thank you both.
