### ISSUE TITLE
Cmake third_party: not contain CMakeLists.txt

### ISSUE THREAD

**Issue by anny0316** [PyMesh/PyMesh#219]
I follow the commands cmake third-party library:
cd $PYMESH_PATH/third_party
mkdir build
cd build
cmake ..
make
make install

and the result prompts:
CMake Error: The source directory "$PYMESH_PATH/third_party" does not appear to contain CMakeLists.txt.

I have confirmed that there is no CMakeLists.txt file in the third-party library. Did I make a mistake?

**Comment by charlie0389** [comment]
I also am getting the same issue. I note that there is a build.py file, but this comes with a few problems that makes it using it unwieldy. Specifically, there is no 'all' option, and when I attempt to use the script going through dependencies 1-by-1 I get a failure on the first one (cgal) with the same issue (no CMakeLists).

**Comment by charlie0389** [comment]
I've tried going back to a previous commit (bb0bac9db4088f841ef3441f495f530babfd1339 which was made on the 13/10, which is well before the "Overhaul third party build process." commit which I suspect is causing the issue). However, this does not work - I get a "error: Server does not allow request for unadvertised object...".

**Comment by qnzhou** [comment]
Yes, sorry about the confusion.  Please try using the `setup.py build` script for building both the third party and the main PyMesh code.

It is still possible to just build third party libraries by themselves, I have provided a build python script:

```sh
cd third_party
./build.py cgal
./build.py eigen
./build.py triangle
./build.py tetgen
./build.py clipper
./build.py qhull
./build.py cork
./build.py draco
./build.py tbb
./build.py mmg
```

**Comment by anny0316** [comment]
Thank you very much, Qingnan. I got it.

**Comment by qnzhou** [comment]
I have added an `all` option, and the doc has been updated.  To build third party, you can simply

```sh
cd third_party
./build.py all
```

**Comment by anny0316** [comment]
Thanks a lot. I am most grateful.

**Comment by charlie0389** [comment]
Hi, but I don't think this issue should be closed because this has not resolved the issue - the command:

    python build.py all

Returns the error: CMake Error: The source directory "/home/speedygonzales/Projects/PyMesh/third_party/build/cgal" does not appear to contain CMakeLists.txt.

**Comment by qnzhou** [comment]
Can you let me know your cmake version?

```
cmake --version
```

The build script assumes `-B <build_dir>` options is supported, which requires cmake 3.13.5 and above.  Maybe that is why?

**Comment by charlie0389** [comment]
Ah yes, you are correct, but this is because the system cmake is used (Ubuntu 18.04 does not have cmake of the required version in the repositories). Could an option be added to specify the cmake bin? This would be very useful because it would enable everyone using Ubuntu 18.04 and older to use your package without having to go through a custom install process for cmake (which would involve overriding the system cmake).

**Comment by qnzhou** [comment]
@charlie0389 I have updated the build script.  It should work for older cmake now.  Please let me know if it is still an issue.

**Comment by charlie0389** [comment]
Thanks @qnzhou

**Comment by anny0316** [comment]
Hello, Qingnan!
When ./build.py draco, an error occurs: 'size_t' does not name a type. I downloaded draco again from https://github.com/google/draco, but the error still exists.  How do I do it?

**Comment by anny0316** [comment]
The error message is as follows:
In file included from /home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.cc:15:0:
/home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.h:26:1: error: ‘size_t’ does not name a type
/home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.h:33:1: error: ‘size_t’ does not name a type
/home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.h:43:43: error: ‘size_t’ has not been declared
/home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.h:48:3: error: ‘size_t’ does not name a type
/home/project/pro/masif/tool/PyMesh/third_party/draco/src/draco/core/hash_utils.h:57:3: error: ‘size_t’ does not name a type
CMakeFiles/draco_core.dir/build.make:166: recipe for target 'CMakeFiles/draco_core.dir/src/draco/core/hash_utils.cc.o' failed
make[2]: *** [CMakeFiles/draco_core.dir/src/draco/core/hash_utils.cc.o] Error 1
CMakeFiles/Makefile2:1166: recipe for target 'CMakeFiles/draco_core.dir/all' failed
make[1]: *** [CMakeFiles/draco_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by anny0316** [comment]
Hello, Qingnan!
When ./build.py draco, an error occurs: error: expected ‘;’ at end of member declaration.
How do I do it?
![111](https://user-images.githubusercontent.com/43496750/72954792-86abf980-3dd4-11ea-8f90-7f001566aab0.png)

**Comment by aarchiba** [comment]
I seem to be encountering this same error with current pymesh - I have cmake 3.13.4 and I get:
```
$ python build.py cork
CMake Error: The source directory "/home/archibald/software/pymesh/PyMesh/third_party/cork" does not appear to contain CMakeLists.txt.
(...)
```

It is running cmake as
```
$ cmake /home/archibald/software/pymesh/PyMesh/third_party/../third_party/cork -DBUILD_SHARED_LIBS=Off -DCMAKE_POSITION_INDEPENDENT_CODE=On -DCMAKE_INSTALL_PREFIX=/home/archibald/software/pymesh/PyMesh/third_party/../python/pymesh/third_party/
CMake Error: The source directory "/home/archibald/software/pymesh/PyMesh/third_party/cork" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by Nikolatesla-lj** [comment]
> @charlie0389 I have updated the build script. It should work for older cmake now. Please let me know if it is still an issue.

It still exists the same issue when the cmake version is 3.10.2.

**Comment by SimonSolar2C** [comment]
Hi @qnzhou 
After build using your instruction above, I try pymesh function and am getting error:
 pymesh' has no attribute 'distance_to_mesh'
It states elsewhere ( https://github.com/PyMesh/PyMesh/issues/37) that it is caused by failure of CGAL to build.  But I think it has built.  I ran  it again and attach herewith a log file, and screen grab.
Can you please help ?
[cgal.log](https://github.com/PyMesh/PyMesh/files/4525922/cgal.log)
![CGAL-prob](https://user-images.githubusercontent.com/12725844/80161132-7d286c80-8623-11ea-90e2-e30b572a7526.jpg)

**Comment by SimonSolar2C** [comment]
Hello @Cascades - am I using it wrong?
_Distance to mesh query
pymesh.distance_to_mesh(mesh, pts, engine=’auto’)
Compute the distance from a set of points to a mesh._

https://buildmedia.readthedocs.org/media/pdf/pymesh/latest/pymesh.pdf

**Comment by SimonSolar2C** [comment]
Okay I think I was using it wrong.
I think I have it right, though ,I am now recieving an assert:
```
python3: /home/simon/PyMesh/third_party/libigl/include/igl/AABB.cpp:480: void ig             l::AABB<DerivedV, DIM>::squared_distance(const Eigen::MatrixBase<Derived>&, cons             t Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, Eige             n::PlainObjectBase<Derivedelements>&, Eigen::PlainObjectBase<DerivedI>&, Eigen::             PlainObjectBase<DerivedC>&) const [with DerivedEle = Eigen::Matrix<int, -1, -1,              1>; DerivedP = Eigen::Matrix<double, -1, -1, 1>; DerivedsqrD = Eigen::Matrix<dou             ble, -1, 1>; DerivedI = Eigen::Matrix<int, -1, 1>; DerivedC = Eigen::Matrix<doub             le, -1, -1, 1>; DerivedV = Eigen::Matrix<double, -1, -1, 1>; int DIM = 3]: Asser             tion `P.cols() == V.cols() && "cols in P should match dim of cols in V"' failed.
Aborted (core dumped)
 
```
And the code snippet I am running:
...
```
import pymesh
mymesh = pymesh.load_mesh(stlfilein)
x = np.array([5.5, 8.7, 4.1])
pymesh.distance_to_mesh(mymesh, x, 'auto')

```
Am I using it wrong @qnzhou @Cascades ?

**Comment by SimonSolar2C** [comment]
Replying to myself, for others benefit, distance_to_mesh requires that the array has more than one 3 dimensional element. I also specified "cgal" engine and my function returns results:
```
x = np.array([[5.5, 8.7, 4.1],[5.05,8.6,4.0002]])
print ("Test its accesible-all:", x, "One X element:", x[0])
print (" - distance to object:", pymesh.distance_to_mesh(mymesh, x, "cgal"))
```
Results:
```
 - distance to object: (array([ 0.03630993,  0.41484448]), array([555, 555], dtype=int32), array([[ 5.69040824,  8.7       ,  4.1073915 ],
       [ 5.69359947,  8.6       ,  4.02518404]]))
```

**Comment by Cascades** [comment]
@SimonSolar2C It should work for only one point as long as you use a 2D array. You need to pass through an array of points (in array form) as oppose to an array of floats (like your first example).

```
import pymesh
mymesh = pymesh.load_mesh(stlfilein)
x = np.array([[5.5, 8.7, 4.1]])
pymesh.distance_to_mesh(mymesh, x)
```

This should work.

**Comment by YunYunY** [comment]
> > @charlie0389 I have updated the build script. It should work for older cmake now. Please let me know if it is still an issue.
> 
> It still exists the same issue when the cmake version is 3.10.2.

I also have the same error when using cmake 3.10.2-1ubuntu2.18.04.1
Is there a way to fix this now? 
Thank you.

**Comment by schliffen** [comment]
I followed all instructions above in Ubuntu 18.04; same Error:
CMake Error: The source directory "/home/ai/install/PyMesh/third_party/Clipper/cpp" does not exist

**Comment by sakshambh** [comment]
> 



> I followed all instructions above in Ubuntu 18.04; same Error: CMake Error: The source directory "/home/ai/install/PyMesh/third_party/Clipper/cpp" does not exist
could you please help me with the same?
