### ISSUE TITLE
Angle Based Flattening Implementation in PyMesh?

### ISSUE THREAD

**Issue by wcheung-code** [PyMesh/PyMesh#249]
Hello, I have been looking for Python compatible code to perform Angle Based Flattening (https://www.cs.ubc.ca/~sheffa/ABF++/abf.htm) on a given mesh. I am wondering if this functionality currently exists or if this can be easily reproduced using the current functionalities in PyMesh. Any direction would help me. Thanks!

**Comment by Rasoul20sh** [comment]
Hello,
Did you find your answer?
