### ISSUE TITLE
build error on ubuntu20.04 ---> can't find the <python.h> file

### ISSUE THREAD

**Issue by yangma0** [PyMesh/PyMesh#262]
[ 90%] Building CXX object python/CMakeFiles/PyMesh.dir/module.cpp.o
In file included from /home/young/PyMesh/third_party/pybind11/include/pybind11/pytypes.h:12,
                 from /home/young/PyMesh/third_party/pybind11/include/pybind11/cast.h:13,
                 from /home/young/PyMesh/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/young/PyMesh/third_party/pybind11/include/pybind11/pybind11.h:44,
                 from /home/young/PyMesh/python/module.cpp:3:
/home/young/PyMesh/third_party/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
  112 | #include <Python.h>
      |          ^~~~~~~~~~

Thank you 😁😁

**Comment by MCemGunes** [comment]
Hello @GakkiIIIII,
I have the exact same problem. `make` process is corrupted in 90% 

`
[ 90%] Building CXX object python/CMakeFiles/PyMesh.dir/module.cpp.o
In file included from /home/USER/git_repository/PyMesh/third_party/pybind11/include/pybind11/pytypes.h:12,
                 from /home/USER/git_repository/PyMesh/third_party/pybind11/include/pybind11/cast.h:13,
                 from /home/USER/git_repository/PyMesh/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/USER/git_repository/PyMesh/third_party/pybind11/include/pybind11/pybind11.h:44,
                 from /home/USER/git_repository/PyMesh/python/module.cpp:3:
/home/USER/git_repository/PyMesh/third_party/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
  112 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [python/CMakeFiles/PyMesh.dir/build.make:63: python/CMakeFiles/PyMesh.dir/module.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2315: python/CMakeFiles/PyMesh.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`
Using Ubuntu 20.04.2 LTS

How did you manage to solve this problem?

**Comment by yanliang3612** [comment]
hi, i have meeted the same problems, how do u adress it?

**Comment by MCemGunes** [comment]
> hi, i have meeted the same problems, how do u adress it?

Hello, Unfortunately, it has been a long time since I have tried, I will try to check it and update you.
