### ISSUE TITLE
Could NOT find GMP (missing: GMP_LIBRARIES GMP_INCLUDE_DIR)

### ISSUE THREAD

**Issue by bernakabadayi** [PyMesh/PyMesh#293]
Hi,

Is there anyone who can successfully build pymesh on Ubuntu conda environment? When I follow Build with Setuptools I got the following error.
![Screenshot 2021-04-25 at 20 29 32](https://user-images.githubusercontent.com/9625842/116003013-f2e36180-a604-11eb-9c4c-546d8237c310.png)

Secondly, I tried to build with CMake but there is no Cmakefile in the path $PYMESH_PATH/third_party as suggested on the website. https://pymesh.readthedocs.io/en/latest/installation.html
![Screenshot 2021-04-25 at 20 29 10](https://user-images.githubusercontent.com/9625842/116003000-e65f0900-a604-11eb-941e-281b2006eae7.png)

Thanks!
Berna

**Comment by dangom** [comment]
After facing the same issue:
Download the latest gmp, extract it, build it, install it, let cmake know where to find it.

```sh
PREFIX=/my/target/install/location  # Change this to install GMP wherever you want.

curl -fLO https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
tar -xf gmp-6.2.1.tar.xz
cd gmp-6.2.1
./configure --prefix=$PREFIX
make all
make install
cp gmpxx.h $PREFIX/include
export GMP_INC=$PREFIX/include
export GMP_LIB=$PREFIX/lib
```

**Comment by jflucier** [comment]
sudo apt-get install libmpfr-dev, libgmp-dev, libboost-all-dev

solves it on ubuntu

**Comment by aryan-at-ul** [comment]
same issue on amazon linux, any fix for that ?

**Comment by suniljalandhra** [comment]
> sudo apt-get install libmpfr-dev,

same issue on amazon Linux, how to fix that?

**Comment by ShaokangXie** [comment]
> > sudo apt-get install libmpfr-dev,
> 
> same issue on amazon Linux, how to fix that?

Maybe you can try 
```
sudo yum install gmp-static
```

**Comment by a0405u** [comment]
> sudo apt-get install libmpfr-dev, libgmp-dev, libboost-all-dev
> 
> solves it on ubuntu

Same works for Debian:
`sudo apt install libmpfr-dev, libgmp-dev, libboost-all-dev`
