### ISSUE TITLE
does pymesh run on windows

### ISSUE THREAD

**Issue by AhmedAchraf2001** [PyMesh/PyMesh#341]
Hi! I tried to install pymesh using `py -m pip install pymesh2` and have received the following error:
https://pastebin.com/n2VyLSYp

I first tried to install pymesh but I couldn't use` pymesh.load_mesh() `and realized I was using the wrong library

**Comment by Cascades** [comment]
You could try this https://github.com/PyMesh/PyMesh/issues/330
